# Welcome to Jekyll!
title: Pablo Quintana - Online Resume
url: 
baseurl: 

# Sass setting
sass:
  sass_dir: _sass
  style: compressed

# Custom
lang: en
open: true                  # show or hide your resume
allow_search_engines: true  # allow your resume indexing by search engine, 'true' or 'false'
analytics:
  google:                   # google analytics
  cloudflare:               # cloudflare analytics
  umami:
    script: https://paquintana.github.io/u.js         # umami analytics script src (Replace it with your own config)
    website_id: af636e2d-31ae-46f1-9071-82b1745143a9  # umami analytics website id (Replace it with your own config)
    domains: paquintana.github.io                     # umami analytics domains (Replace it with your own config)
description:
open_graph:
  enable: true                        # enable open graph meta tags
  image: /assets/images/profile.png   # open graph image path

# Style
text_direction: ltr         # text direction, 'ltr' or 'rtl'
date_format: "%Y-%m-%d"     # date format
theme_color: "#80BCBD"      # your favorite theme color
contact_delimiter: "·"      # contact delimiter, '·', '/' or '|'
section_icon: true          # section title icon, true or false
section_title: uppercase    # section title style, 'uppercase', 'lowercase', 'capitalize' or 'none'
section_align: start        # section title align, 'start', 'end' or 'center'
section_line: solid         # section title line, 'solid', 'dashed' or 'none'
section_background: true    # section title backound, 'true' or 'false'
skill_level_icon: star      # skill rate icon, 'heart', 'star', 'circle' or 'lightbulb'
link_icon: true             # show link icon, 'true' or 'false'
site_footer: false          # show site footer, 'true' or 'false'
